/**
 * Built-in example plugin — appends a small disclaimer comment to the
 * top-level README.md if the project has one. Demonstrates the
 * EnhancementPatch contract end-to-end without requiring third-party deps.
 *
 * Disabled by default. Set `ENABLE_EXAMPLE_PLUGIN=1` to register it at
 * server start.
 */

import type { PipelinePlugin } from './types.js';
import type { EnhancementPatch } from '../enhancement-patch.js';

export const exampleReadmeStamper: PipelinePlugin = {
  id: 'example.readme-stamper',
  name: 'README stamper',
  hook: 'after-validate',
  priority: 100,
  run(ctx) {
    const readme = ctx.files.find((f) => f.path.toLowerCase() === 'readme.md');
    if (!readme) return { notes: 'no README.md to stamp' };
    const stamp = `\n\n<!-- Generated by AutoCoder pipeline @ ${new Date().toISOString()} -->\n`;
    if (readme.content.includes('Generated by AutoCoder pipeline')) {
      return { notes: 'already stamped' };
    }
    const patch: EnhancementPatch = {
      source: 'plugin:example.readme-stamper',
      reason: 'Append generation timestamp to README',
      codeChanges: [
        {
          path: readme.path,
          language: readme.language || 'markdown',
          content: readme.content.trimEnd() + stamp,
        },
      ],
    };
    return { patch, notes: 'stamped readme' };
  },
};
