import JSZip from 'jszip';

export interface ExportFile {
  path: string;
  content: string;
  language?: string;
}

export interface ExportOptions {
  projectName: string;
  includeReadme: boolean;
  includeGitignore: boolean;
  includeLicense: boolean;
  includeEnvExample: boolean;
  format: 'zip' | 'tar';
}

// ── Boilerplate file generators ────────────────────────────────────────────────

function generateReadme(projectName: string, files: ExportFile[]): string {
  const hasPackageJson = files.some(f => f.path.includes('package.json'));
  const hasServer = files.some(f => f.path.includes('server'));
  const hasPython = files.some(f => f.path.endsWith('.py'));

  let readme = `# ${projectName}\n\nGenerated by AutoCoder — AI-Powered Code Generator\n\n`;
  readme += `## Project Structure\n\n\`\`\`\n${files.map(f => f.path).join('\n')}\n\`\`\`\n\n`;
  readme += `## Getting Started\n\n`;

  if (hasPackageJson) {
    readme += `### Install dependencies\n\n\`\`\`bash\nnpm install\n\`\`\`\n\n`;
    readme += `### Start development server\n\n\`\`\`bash\nnpm run dev\n\`\`\`\n\n`;
  }

  if (hasPython) {
    readme += `### Python setup\n\n\`\`\`bash\npip install -r requirements.txt\npython main.py\n\`\`\`\n\n`;
  }

  if (hasServer) {
    readme += `The app runs on **http://localhost:5000** by default.\n\n`;
  }

  readme += `## Environment Variables\n\nCopy \`.env.example\` to \`.env\` and fill in your values before starting.\n`;
  return readme;
}

function generateGitignore(): string {
  return `# Dependencies
node_modules/
.pnp
.pnp.js

# Build outputs
dist/
build/
.next/
out/
.nuxt/

# Environment variables
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*
*.log

# Editor directories
.vscode/
.idea/
*.swp
*.swo
.DS_Store
Thumbs.db

# TypeScript cache
*.tsbuildinfo

# Database files
*.db
*.sqlite
*.sqlite3
drizzle/
`;
}

function generateEnvExample(files: ExportFile[]): string {
  const envVars = new Set<string>();
  const envPattern = /(?:process\.env|import\.meta\.env)\.([A-Z_][A-Z0-9_]*)/g;
  for (const file of files) {
    let match: RegExpExecArray | null;
    while ((match = envPattern.exec(file.content)) !== null) {
      if (match[1] !== 'NODE_ENV') {
        envVars.add(match[1]);
      }
    }
  }

  const lines = [
    '# Copy this file to .env and fill in your values',
    '# Never commit .env to version control',
    '',
  ];

  if (envVars.size === 0) {
    lines.push('DATABASE_URL=postgresql://localhost:5432/myapp');
  } else {
    for (const v of Array.from(envVars).sort()) {
      lines.push(`${v}=`);
    }
  }
  return lines.join('\n') + '\n';
}

function generateLicense(projectName: string): string {
  const year = new Date().getFullYear();
  return `MIT License

Copyright (c) ${year} ${projectName}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
`;
}

// ── Core export functions ──────────────────────────────────────────────────────

export async function exportProjectAsZip(
  files: ExportFile[],
  options: ExportOptions
): Promise<Blob> {
  const zip = new JSZip();
  const rootDir = options.projectName
    .replace(/[^a-z0-9-_]/gi, '-')
    .toLowerCase()
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '') || 'project';

  const folder = zip.folder(rootDir)!;

  // Add all project files
  for (const file of files) {
    folder.file(file.path, file.content);
  }

  // Add optional boilerplate files
  if (options.includeReadme) {
    folder.file('README.md', generateReadme(options.projectName, files));
  }
  if (options.includeGitignore) {
    folder.file('.gitignore', generateGitignore());
  }
  if (options.includeEnvExample) {
    folder.file('.env.example', generateEnvExample(files));
  }
  if (options.includeLicense) {
    folder.file('LICENSE', generateLicense(options.projectName));
  }

  return zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });
}

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Revoke after a delay to allow the download to start
  setTimeout(() => URL.revokeObjectURL(url), 15_000);
}

export async function downloadProjectAsZip(
  files: ExportFile[],
  projectName: string
): Promise<void> {
  const safeName = (projectName || 'project')
    .replace(/[^a-z0-9-_]/gi, '-')
    .toLowerCase()
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '') || 'project';

  const blob = await exportProjectAsZip(files, {
    projectName: safeName,
    includeReadme: true,
    includeGitignore: true,
    includeLicense: false,
    includeEnvExample: true,
    format: 'zip',
  });

  downloadBlob(blob, `${safeName}.zip`);
}
